### ISSUE TITLE
Text and Video has not  property panel

### ISSUE THREAD

**Issue by qiangzi0303** [salgum1114/react-design-editor#100]
I get the source code and compiled success, i drag the Text control to the panel, but it does not have property panel ,like bellow 

![image](https://user-images.githubusercontent.com/10596105/56420430-7f4d4200-62d0-11e9-91e2-fb4ac8dd7858.png

why?  thanks

**Comment by salgum1114** [comment]
Hi, qiangzi0303

Check it out and let me know

**Comment by SaberDingQ** [comment]
Hi,I check it out and run start:dev. Then find the every compenent dosen't have property.But your demo work normally

**Comment by SaberDingQ** [comment]
> Hi, qiangzi0303
> 
> Check it out and let me know

Hi,I check it out and run start:dev. Then find the every compenent dosen't have property.But your demo work normally

**Comment by salgum1114** [comment]
@qiangzi0303, @SaberDingQ 

It seems to be a problem with the version of the tabs component of ant.design.

The latest version `3.16.3` to `3.15.0` down to use the version will work normally.

**Comment by salgum1114** [comment]
@qiangzi0303, @SaberDingQ 
Please try npm install again to downgrade the ant.design version.

**Comment by qiangzi0303** [comment]
@salgum1114   solved this issue by downgrade the ant.design version. thank you very much.  And i have downloaded the latest source code, it has one error when npm install, even resolved this fault, there is nothing in the http：//localhost:8080 webpage ,please check it.  Thanks for your patience.
