### ISSUE TITLE
[Feature] Socket.io for shapes

### ISSUE THREAD

**Issue by ranajeex** [salgum1114/react-design-editor#103]
Hello Admin

I wanted to implement socket.io for this project like whiteboard feature for all shapes.
https://socket.io/demos/whiteboard/

Can you guide me how can I do that in this project.

Thanks.

**Comment by salgum1114** [comment]
Hi @ranajeex !

First, thank you for your interest in this project.

Are you sure you want to receive data in the React Design Editor via Websocket?

Can you tell me where you want to attach the Websocket?

**Comment by ranajeex** [comment]
Hi @salgum1114 !

Thanks for your response.
Yes I am able to send data from client to sever using websockets.
But I am not able to show data(shapes or freehand drawings) from one browser to another browser.

I have created a server.js file first and serted server(using node src/server.js in terminal):

`const express = require('express');
const path = require('path');
const fs = require('fs');
const http = require('http');
const https = require('https');
const sio = require('socket.io');

const privateKey  = fs.readFileSync(__dirname + '/localhost.key');
const certificate = fs.readFileSync(__dirname + '/localhost.cert');

const credentials = {key: privateKey, cert: certificate};

const app = express();

server = https.createServer(credentials, app);
server.listen(4000, function() {
	console.log("Express server listening on port: 4000");
});
io = sio(server);
  socket.on('drawshapes', (data) => {
    console.log('drawshapes:--', data);
    socket.broadcast.emit('drawing', data)
  });
});
`

After that created socket client on src/components/cancas/canvas.js

`import openSocket from 'socket.io-client';

const socket = openSocket(`${process.env.APP_HOST}:${process.env.APP_PORT}`);`

Now I have to emit drawing / shapes to server and it should show the same from one browser to another browser:

`socket.emit('drawshapes', {
                    x0: 210,
                    y0: 450,
                    x1: 150,
                    y1: 550,
                    color: '#000000'
              });`

Please correct me where I am doing wrong.

**Comment by salgum1114** [comment]
@ranajeex 

Sorry for the late reply.

`Canvas.js` component has `onAdd`, `onModified` Props. Can you try emit in this function?

onAdd, onModifed is a parameter passed as `target`, which is a canvas object.

As an example of your example,

```javascript
onAdd = (target) => {
   socket.emit ('drawshapes', {x0: target.x0, y0: target.y0, x1: target.x1, y1: target.y1, color: target.color});
}
```

I think I can do it this way.

**Comment by ranajeex** [comment]
@salgum1114 

Thanks for your suggestion.
I will try the same and get back to you.
