### ISSUE TITLE
[Feature] Freehand drawing using websockets

### ISSUE THREAD

**Issue by ranajeex** [salgum1114/react-design-editor#107]
Hello @salgum1114,

I am trying to implement freehand drawing using websockets.

Just like: https://socket.io/demos/whiteboard/

Please find the attachment for the canvas and node server reference.

[wb.zip](https://github.com/salgum1114/react-design-editor/files/3227416/wb.zip)

I appreciate if you can suggest some solutions for the same.

Thanks!

**Comment by ranajeex** [comment]
Hello @salgum1114,

Please find the issue, I am facing while developing freehand drawing:

![AwesomeScreenshot-2019-5-29-1559136310797](https://user-images.githubusercontent.com/50329137/58561229-447de880-8244-11e9-9969-45395e29c108.gif)

**Comment by salgum1114** [comment]
@ranajeex 

[Fabric.js freehand drawing example][example]

I think you should check it out.

[example]: http://fabricjs.com/freedrawing

**Comment by ranajeex** [comment]
@salgum1114,

I have checked this example: http://fabricjs.com/freedrawing

And implemented as well in this application but i am facing some issue as shown in above video.

Please check once my implementation in below code:

https://github.com/salgum1114/react-design-editor/files/3227416/wb.zip

I appreciate if you would provide some suggestion on that.

Thanks.

**Comment by shahilpb** [comment]
Hi @ranajeex ,
did you get solution on above issue?
