### ISSUE TITLE
Websockets implementation for scaling, moving and rotating objects

### ISSUE THREAD

**Issue by ranajeex** [salgum1114/react-design-editor#108]
Hello @salgum1114,

I am trying to implement websockets to scale, move and rotate objects using websockets.
Something like: https://fabricjs-collaboration.herokuapp.com/fabric

Please find the attachment for my implementation.
[wb.zip](https://github.com/salgum1114/react-design-editor/files/3227432/wb.zip)

Please suggest where I am doing wrong.

Thanks!

**Comment by salgum1114** [comment]
Hi @ranajeex 

I have not tried it, but I'll test it and let you know.

**Comment by salgum1114** [comment]
@ranajeex 

I saw and developed the example you gave me.
Is this what you are trying to do?

![react-design-editor-websocket2](https://user-images.githubusercontent.com/19975642/58542845-3f676c00-8239-11e9-822b-d85465619402.gif)

The code looks like this.

**server.ts**
```javascript
import WebSocket from 'ws';

const wss = new WebSocket.Server({ port: 80 });

wss.broadcast = function broadcast(data) {
    wss.clients.forEach(function each(client) {
        if (client.readyState === WebSocket.OPEN) {
            client.send(data);
        }
    });
};

wss.on('connection', (ws: WebSocket) => {
    console.log('Connected Client');
    ws.on('message', function incoming(data) {
        // Broadcast to everyone else.
        console.log('Received', data);
        wss.clients.forEach(function each(client) {
            if (client !== ws && client.readyState === WebSocket.OPEN) {
                client.send(data);
            }
        });
    });
});
```

**ImageMapEditor.js**
```javascript
...code...
componentDidMount() {
    this.showLoading(true);
    import('./Descriptors.json').then((descriptors) => {
        this.setState({
            descriptors,
        }, () => {
            this.showLoading(false);
        });
    });
    this.resizeSensor = new ResizeSensor(this.container, () => {
        const { canvasRect: currentCanvasRect } = this.state;
        const canvasRect = Object.assign({}, currentCanvasRect, {
            width: this.container.clientWidth,
            height: this.container.clientHeight,
        });
        this.setState({
            canvasRect,
        });
    });
    this.setState({
        canvasRect: {
            width: this.container.clientWidth,
            height: this.container.clientHeight,
        },
        selectedItem: null,
    });
    this.websocket = new WebSocket('ws://localhost');
    this.websocket.onopen = (e) => {
        this.id = uuid();
        console.log('Opened websocket', e.type);
    };
    this.websocket.onmessage = (e) => {
        const data = JSON.parse(e.data);
        const { type, target } = data;
        if (type === 'add') {
            this.canvasRef.handlers.add(target, false, true, false);
        } else if (type === 'modified') {
            const findObj = this.canvasRef.handlers.findById(target.id);
            this.canvasRef.handlers.setByPartial(findObj, target);
        }
        console.log('Received message', data);
    };
}

canvasHandlers = {
    ...code...
    onAdd: (target) => {
        if (!this.state.editing) {
            this.changeEditing(true);
        }
        if (target.type === 'activeSelection') {
            this.canvasHandlers.onSelect(null);
            return;
        }
        this.canvasRef.handlers.select(target);
        this.websocket.send(JSON.stringify({
            id: this.id,
            type: 'add',
            target: target.toObject(propertiesToInclude),
        }));
    },
    ...code...
    onModified: debounce((target) => {
        if (!this.state.editing) {
            this.changeEditing(true);
        }
        if (target
        && target.id
        && target.id !== 'workarea'
        && target.type !== 'activeSelection') {
            this.canvasRef.transactionHandlers.save(target, 'modified');
            this.setState({
                selectedItem: target,
            });
            this.websocket.send(JSON.stringify({
                id: this.id,
                type: 'modified',
                target: target.toObject(propertiesToInclude),
            }));
            return;
        }
        this.setState({
            selectedItem: null,
        });
    }, 300),
    ...code....
}
...code...
```
Based on this code I think you can do the real time drawing you want.

![react-design-editor-websocket](https://user-images.githubusercontent.com/19975642/58543558-a6d1eb80-823a-11e9-83ac-cd00d7f771f2.gif)

**Comment by ranajeex** [comment]
@salgum1114 

Thanks for the code.

I will check the same and get back to you if any issue.

**Comment by ranajeex** [comment]
Yes this is exactly what i am trying to do.

I have tried your sample but I ended up with some error:

`Uncaught Error: ws does not work in the browser. Browser clients must use the native WebSocket object
    at new push../node_modules/ws/browser.js.module.exports (browser.js:4)
    at ProxyComponent.componentDidMount (ImageMapEditor.js:129)
    at ProxyComponent.componentDidMount (react-hot-loader.development.js:572)
    at commitLifeCycles (react-dom.development.js:17334)
    at commitAllLifeCycles (react-dom.development.js:18736)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at commitRoot (react-dom.development.js:18948)
    at react-dom.development.js:20418
push../node_modules/ws/browser.js.module.exports @ browser.js:4
componentDidMount @ ImageMapEditor.js:129
componentDidMount @ react-hot-loader.development.js:572
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
ImageMapHeaderToolbar.js:98 Uncaught TypeError: Cannot read property 'canvas' of undefined
    at ProxyComponent.detachEventListener (ImageMapHeaderToolbar.js:98)
    at ProxyComponent.componentWillUnmount (ImageMapHeaderToolbar.js:76)
    at ProxyComponent.componentWillUnmount (react-hot-loader.development.js:572)
    at callComponentWillUnmountWithTimer (react-dom.development.js:17169)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at safelyCallComponentWillUnmount (react-dom.development.js:17176)
    at commitUnmount (react-dom.development.js:17553)
    at commitNestedUnmounts (react-dom.development.js:17584)
(anonymous) @ ImageMapHeaderToolbar.js:98
componentWillUnmount @ ImageMapHeaderToolbar.js:76
componentDidMount @ react-hot-loader.development.js:572
callComponentWillUnmountWithTimer @ react-dom.development.js:17169
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
safelyCallComponentWillUnmount @ react-dom.development.js:17176
commitUnmount @ react-dom.development.js:17553
commitNestedUnmounts @ react-dom.development.js:17584
unmountHostComponents @ react-dom.development.js:17845
commitDeletion @ react-dom.development.js:17904
commitAllHostEffects @ react-dom.development.js:18685
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18913
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
ImageMapFooterToolbar.js:46 Uncaught TypeError: Cannot read property 'canvas' of undefined
    at ProxyComponent.detachEventListener (ImageMapFooterToolbar.js:46)
    at ProxyComponent.componentWillUnmount (ImageMapFooterToolbar.js:27)
    at ProxyComponent.componentWillUnmount (react-hot-loader.development.js:572)
    at callComponentWillUnmountWithTimer (react-dom.development.js:17169)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at safelyCallComponentWillUnmount (react-dom.development.js:17176)
    at commitUnmount (react-dom.development.js:17553)
    at commitNestedUnmounts (react-dom.development.js:17584)
(anonymous) @ ImageMapFooterToolbar.js:46
componentWillUnmount @ ImageMapFooterToolbar.js:27
componentDidMount @ react-hot-loader.development.js:572
callComponentWillUnmountWithTimer @ react-dom.development.js:17169
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
safelyCallComponentWillUnmount @ react-dom.development.js:17176
commitUnmount @ react-dom.development.js:17553
commitNestedUnmounts @ react-dom.development.js:17584
unmountHostComponents @ react-dom.development.js:17845
commitDeletion @ react-dom.development.js:17904
commitAllHostEffects @ react-dom.development.js:18685
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18913
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
react-dom.development.js:17117 The above error occurred in the <ImageMapEditor> component:
    in ImageMapEditor (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App
    in AppContainer
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:17117
logError @ react-dom.development.js:17153
callback @ react-dom.development.js:18094
callCallback @ react-dom.development.js:16433
commitUpdateEffects @ react-dom.development.js:16472
commitUpdateQueue @ react-dom.development.js:16460
commitLifeCycles @ react-dom.development.js:17364
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
react-hot-loader.development.js:175 Error: ws does not work in the browser. Browser clients must use the native WebSocket object
    at new push../node_modules/ws/browser.js.module.exports (browser.js:4)
    at ProxyComponent.componentDidMount (ImageMapEditor.js:129)
    at ProxyComponent.componentDidMount (react-hot-loader.development.js:572)
    at commitLifeCycles (react-dom.development.js:17334)
    at commitAllLifeCycles (react-dom.development.js:18736)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at commitRoot (react-dom.development.js:18948)
    at react-dom.development.js:20418
error @ react-hot-loader.development.js:175
componentDidCatch @ react-hot-loader.development.js:1564
notifySubscribers @ react-hot-loader.development.js:582
callback @ react-dom.development.js:18095
callCallback @ react-dom.development.js:16433
commitUpdateEffects @ react-dom.development.js:16472
commitUpdateQueue @ react-dom.development.js:16460
commitLifeCycles @ react-dom.development.js:17364
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
react-dom.development.js:17117 The above error occurred in the <ImageMapHeaderToolbar> component:
    in ImageMapHeaderToolbar (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by Container)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by Container)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Spin (created by Container)
    in Container (created by ImageMapEditor)
    in ImageMapEditor (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App
    in AppContainer
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:17117
logError @ react-dom.development.js:17153
callback @ react-dom.development.js:18094
callCallback @ react-dom.development.js:16433
commitUpdateEffects @ react-dom.development.js:16472
commitUpdateQueue @ react-dom.development.js:16460
commitLifeCycles @ react-dom.development.js:17364
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
react-hot-loader.development.js:175 TypeError: Cannot read property 'canvas' of undefined
    at ProxyComponent.detachEventListener (ImageMapHeaderToolbar.js:98)
    at ProxyComponent.componentWillUnmount (ImageMapHeaderToolbar.js:76)
    at ProxyComponent.componentWillUnmount (react-hot-loader.development.js:572)
    at callComponentWillUnmountWithTimer (react-dom.development.js:17169)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at safelyCallComponentWillUnmount (react-dom.development.js:17176)
    at commitUnmount (react-dom.development.js:17553)
    at commitNestedUnmounts (react-dom.development.js:17584)
error @ react-hot-loader.development.js:175
componentDidCatch @ react-hot-loader.development.js:1564
notifySubscribers @ react-hot-loader.development.js:582
callback @ react-dom.development.js:18095
callCallback @ react-dom.development.js:16433
commitUpdateEffects @ react-dom.development.js:16472
commitUpdateQueue @ react-dom.development.js:16460
commitLifeCycles @ react-dom.development.js:17364
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
react-dom.development.js:17117 The above error occurred in the <ImageMapFooterToolbar> component:
    in ImageMapFooterToolbar (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by Container)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by Container)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Spin (created by Container)
    in Container (created by ImageMapEditor)
    in ImageMapEditor (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App
    in AppContainer
    in Provider

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:17117
logError @ react-dom.development.js:17153
callback @ react-dom.development.js:18094
callCallback @ react-dom.development.js:16433
commitUpdateEffects @ react-dom.development.js:16472
commitUpdateQueue @ react-dom.development.js:16460
commitLifeCycles @ react-dom.development.js:17364
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
react-hot-loader.development.js:175 TypeError: Cannot read property 'canvas' of undefined
    at ProxyComponent.detachEventListener (ImageMapFooterToolbar.js:46)
    at ProxyComponent.componentWillUnmount (ImageMapFooterToolbar.js:27)
    at ProxyComponent.componentWillUnmount (react-hot-loader.development.js:572)
    at callComponentWillUnmountWithTimer (react-dom.development.js:17169)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at safelyCallComponentWillUnmount (react-dom.development.js:17176)
    at commitUnmount (react-dom.development.js:17553)
    at commitNestedUnmounts (react-dom.development.js:17584)
error @ react-hot-loader.development.js:175
componentDidCatch @ react-hot-loader.development.js:1564
notifySubscribers @ react-hot-loader.development.js:582
callback @ react-dom.development.js:18095
callCallback @ react-dom.development.js:16433
commitUpdateEffects @ react-dom.development.js:16472
commitUpdateQueue @ react-dom.development.js:16460
commitLifeCycles @ react-dom.development.js:17364
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
react-dom.development.js:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ImageMapEditor (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App
warningWithoutStack @ react-dom.development.js:506
warnAboutUpdateOnUnmounted @ react-dom.development.js:18475
scheduleWork @ react-dom.development.js:19885
enqueueSetState @ react-dom.development.js:11169
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:335
(anonymous) @ ImageMapEditor.js:105
Promise.then (async)
componentDidMount @ ImageMapEditor.js:104
componentDidMount @ react-hot-loader.development.js:572
commitLifeCycles @ react-dom.development.js:17334
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
react-dom.development.js:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Timer (created by ImageMapHeaderToolbar)
    in div (created by FlexBox)
    in FlexBox (created by ImageMapHeaderToolbar)
    in div (created by FlexBox)
    in FlexBox (created by ImageMapHeaderToolbar)
    in ImageMapHeaderToolbar (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in div (created by ImageMapEditor)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by Container)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by Container)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Spin (created by Container)
    in Container (created by ImageMapEditor)
    in ImageMapEditor (created by App)
    in div (created by App)
    in div (created by App)
    in div (created by App)
    in App
`

**Comment by ranajeex** [comment]
@salgum1114 

How you started server.ts?
Anything else have to do apart from suggestions?

**Comment by salgum1114** [comment]
@ranajeex 

Of course you have to run **server.ts** individually.

I don't know the error you write.

**Comment by ranajeex** [comment]
@salgum1114,

Now its working for me.

Thanks for the help :)
