### ISSUE TITLE
[Bug ? ] Tainted canvases may not be exported

### ISSUE THREAD

**Issue by oscarnevarezleal** [salgum1114/react-design-editor#111]
**Tainted canvases may not be exported**
Hi, first of all. Awesome project.

I having what it seems to be an issue not with the project but its configuration.
Seems like cors has not been configured to use within the canvas. Even when a valid _cors_ response is given by my server; when I try to export an image using the editor I face the error _Tainted canvases may not be exported_.

Is there a way to instruct the editor to tell fabricJs everything is cool with the crossOrigin?
Greetings.

**Comment by salgum1114** [comment]
Hi, Oscar.

First of all, I am using React Design Editor project as a real product.

The CORS issue that occurs when you export the fabric.image seems to be a server-side issue.

Once again, how about checking the server-side CORS policy?

**Comment by oscarnevarezleal** [comment]
Thank you salgum1114.

Sometimes you will add an image to the editor that not necessarily comes from your own server. I understand your product don't have in mind this, that's ok.

**Comment by adteague** [comment]
@oscarnevarezleal did you ever solve this?

**Comment by oscarnevarezleal** [comment]
@adteague nope :/

**Comment by ZhelinCheng** [comment]
Have you solved it?
