### ISSUE TITLE
[Question] How can we save image by layout size?

### ISSUE THREAD

**Issue by markblasdls** [salgum1114/react-design-editor#137]
Hi, can you advise me on how to save the image by its layout size? Like for example if I set the layout to fixed 500x1000 and click Save Image, it should save the layout with 500x1000 size.   Currently, It will save base on the entire canvas and how it was zoomed in and out. 

Thank you very much.

**Comment by salgum1114** [comment]
It does not provide a way to save an image based on Workarea's layout. But there is a way. The easiest way to think about it is to group it into a new group using the `objects` collection, and save it as an image.
