### ISSUE TITLE
[Question] How to update for Heroku

### ISSUE THREAD

**Issue by paulmiller3000** [salgum1114/react-design-editor#138]
Has anyone deployed to Heroku? I've been having problems trying to get the app working on Heroku.

I've gone pretty far down the rabbit hole over the past two days, setting up an Express server and updating my package.json scripts based on environment. After two days of hacking away at it, that feels like overkill.

Hoping I just made a simple mistake. So, I recloned the repo and pushed it out of the gate. The browser is returning the standard Heroku application error. Here's an abbreviated dump from `heroku logs --tail`:

> Starting process with command `npm start`
> 
> > react-design-editor@0.0.16 start /app
> > npm install && npm run start:dev
> 
> > react-design-editor@0.0.16 start:dev /app
> > webpack-dev-server --config webpack.dev.js --inline
> 
> sh: 1: webpack-dev-server: not found
> npm ERR! code ELIFECYCLE
> npm ERR! syscall spawn
> npm ERR! file sh
> npm ERR! errno ENOENT
> npm ERR! react-design-editor@0.0.16 start:dev: `webpack-dev-server --config webpack.dev.js --inline`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the react-design-editor@0.0.16 start:dev script.

**Comment by paulmiller3000** [comment]
I think I'm just about there, albeit with several changes. First, I installed the following packages:

- express
- per-env

Then I created server.js in the root:

```
const express = require('express');
const app = express();
const distDir = 'public';
const path = require('path');
const port = process.env.PORT || 5000;

app.use(express.static(distDir));

app.get('*', (req, res) => {
	res.sendFile(path.resolve(__dirname, 'public', 'index.html'));
})

app.listen(port, () => console.log(`App listening on port ${port}!`))
```

Next, I modified the scripts section of package.json, using per-env variables:

```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "per-env",
    "build:staging": "node clean && webpack -p --config webpack.staging.js",
    "build:production": "node clean && webpack -p --config webpack.prod.js",
    "build:lib": "npm run tsc && webpack -p --config webpack.lib.js",
    "@comment start": [
      "'npm start' is _the_ command to start the server across all environments."
    ],
    "start": "per-env",
    "start:development": "npm install && webpack-dev-server --config webpack.dev.js --inline",
    "start:staging": "node server.js",
    "start:production": "npm run build",
    "deploy": "npm run build:lib && npm publish",
    "lint": "npm run tsc",
    "clean": "node clean",
    "tsc": "tsc"
  },
```

Finally, I added removed `public/index.html` from .gitignore for testing and added a second, generic index.html in the root as a catch-all.

After pushing to Heroku, I get a blank canvas with my application's name. The console isn't returning anything, but inspect shows that /public/index.html is being loaded.

It can't find the js files referenced in the body:

'<script type="text/javascript" src="./js/1.92092d0463a4d93e.js"></script><script type="text/javascript" src="./js/app.653fc38a315081a9.js"></script>'

This test proved the app is now (almost loaded). I'm guessing public/index.html and those JS files are dynamically generated. So, I added public/index.html back to .gitignore, pushed again, and refreshed my cache.

App still loads the blank screen and inspect indicates it's looking for those same file names. 

Using bash, I see that index.html is back on the server. However, I can't find a js directory anywhere.

Am I on the right track? What am I missing?

**Comment by salgum1114** [comment]
There is a `npm run build` script for deployment.
The output of this script is distributed in the `docs` path, not in the` public` directory.

Your `express` code is set to` public` as a static directory. Change this to `docs`.

In addition, `webpack-dev-server` is the web server for your development environment. In order to deploy with `heroku` it is correct to proceed with a` production` build.

**Comment by paulmiller3000** [comment]
Updating my directory from `public` to `docs` solved it. Thank you!
