### ISSUE TITLE
Cannot delete edge

### ISSUE THREAD

**Issue by jvence** [salgum1114/react-design-editor#140]
Can't seem to be able to delete a connection (edge) between 2 nodes. This should be basic functionality but doesn't seem to be working.

**Comment by salgum1114** [comment]
@jvence 

Under what circumstances can Edge not be deleted?

**Comment by jvence** [comment]
@salgum1114 How do you delete it? No option to do so.

**Comment by salgum1114** [comment]
@jvence 

press delete key.

**Comment by jvence** [comment]
@salgum1114 Does not work on Chrome on Mac. Will test on other browser.

**Comment by salgum1114** [comment]
@jvence I don't understand the situation. I do very well...

**Comment by jvence** [comment]
It doesn't work for me on Chrome or Safari. Here's what I did:
1- Installed a clean copy and run 'npm start'
2- Clicked on workflow and created two actions
3- Connected these actions (see img: https://pasteboard.co/ILF1VMW.png)
4- Trying to delete the edge does not work

**Comment by jvence** [comment]
Delete an edge doesn't even work for me on https://salgum1114.github.io/react-design-editor/
on Chrome or Safari on a Mac OS Catalina.

**Comment by salgum1114** [comment]
@jvence 

MacOS del key is fn + delete

**Comment by salgum1114** [comment]
@jvence 

I will add a backspace key

**Comment by jvence** [comment]
Still not working in version 0.19
