### ISSUE TITLE
Using the component as npm package

### ISSUE THREAD

**Issue by jelenamilanovic** [salgum1114/react-design-editor#141]
Hello,

I’m starting a new React project and would like to use your library, but I’m not sure how to set it up and customize it after installation. I took several approaches to import the component and always got an error. I couldn’t find anything in the documentation, so, could you, please, provide an information what to do after npm install, how to import the component into the application?
Of course, I could clone the project and adapt the code to my own needs, but would like to avoid that solution.

**Comment by salgum1114** [comment]
Hello, @jelenamilanovic 

Sorry, it's not documented yet.

The components provided by `npm` only provide the` Canvas` component.

You must implement your own layout.

An example of the function should be implemented by referring to `ImageMapEditor` or` WorkflowEditor`.

**Comment by jelenamilanovic** [comment]
Thanks for the fast response. 
I realized that, but when I tried to import Canvas, I got this error:

![Screenshot_2](https://user-images.githubusercontent.com/32881681/71070563-550f9500-217b-11ea-97f5-a5f9e88e46f4.png)

I inspected files in node_modules folder and saw that the following requirements are missing: 

![Screenshot_1](https://user-images.githubusercontent.com/32881681/71070731-afa8f100-217b-11ea-922d-6cd74f5e03ed.png)

Tried to run some scripts in the module, but without success.

**Comment by salgum1114** [comment]
@jelenamilanovic 

## Usage

```javascript
import React from 'react'
import { Canvas } 'react-design-editor'

class Example extends React.Component {

    ...other

    render() {
        return (
            <Canvas
                required props...
            />
        )
    }
}
```

**Comment by jelenamilanovic** [comment]
Thank you, that solved the problem. I tried with default import and when it failed, tried to import the component from lib and dist folders...

**Comment by kieran-Collins** [comment]
@jelenamilanovic Can you please share the code/steps and how you implemented?
