### ISSUE TITLE
[Bugfix] Set up correct import paths for objects/IFrame.ts and IFrameProperty.js

### ISSUE THREAD

**Issue by radekaz** [salgum1114/react-design-editor#145]
Import paths were wrong (bad letter sizes) and the project don't want to start.

**Comment by salgum1114** [comment]
@radekaz 

Show me how that bug doesn't work

**Comment by radekaz** [comment]
Hi. Sorry for not precise information. 

- src/components/imagemap/properties/PropertyDefinition.js:11 - you import "I**f**rameProperty" when the filename is: "src/components/imagemap/properties/I**F**rameProperty.js",
- that same

After cloning and starting the repository in dev (npm run start:dev) in Ubuntu system I had an error with that import.

**Comment by salgum1114** [comment]
@radekaz 

Can you captures image?

**Comment by radekaz** [comment]
![2020-01-07_12-02](https://user-images.githubusercontent.com/10554536/71893774-d344d300-314c-11ea-8423-8b7d98ebae40.png)

**Comment by salgum1114** [comment]
@radekaz 

I check it. Change the file name `IFrame` -> `Iframe`
