### ISSUE TITLE
[Feature] Link Configuration

### ISSUE THREAD

**Issue by ivall-cell** [salgum1114/react-design-editor#147]
**Is your feature request related to a problem? Please describe.**
I would like to be able to configure the links between the nodes in a similar way to how you can currently configure nodes. 

**Describe the solution you'd like**
When I draw a link between two nodes, I would like to be able to click on the link and have the right sidebar pop out with fields displayed that I can edit and then when the workflow is designed I can then export it with the configuration of the links also included in the JSON.

Please could you let me know if this is possible, and how you might go about doing it?

Many thanks

**Comment by salgum1114** [comment]
Hello, @ivall-cell 

It is very simple.

Currently, Blocked link configuration in Workflow editor. But, you can modify.

First, you have to modify onSelect logic in Workflow Editor Component.

![image](https://user-images.githubusercontent.com/19975642/71789093-ee8be180-306b-11ea-9830-c87763d897e9.png)

Delete line in red box area of picture and then you can select link object.
