### ISSUE TITLE
Workflow Node Configuration - Multiple Tabs

### ISSUE THREAD

**Issue by ivall-cell** [salgum1114/react-design-editor#151]
Hi, 
I'm looking to have multiple tabs displayed in the Node Configuration sidebar (that appears when you select a Node).

Ideally I want to have different tabs with different Components rendered in each tab, how easy would this be to implement/is it something that you might implement in the future?

Many thanks

**Comment by salgum1114** [comment]
@ivall-cell 

It's so simple. You can rewrite tabs you want in `WorkflowConfigurations` component.
