### ISSUE TITLE
Font preview dropdown

### ISSUE THREAD

**Issue by b-b0t** [salgum1114/react-design-editor#153]
Is this a feature that will be added either via an npm package such as https://www.npmjs.com/package/font-picker-react or in the master branch? Would you accept pull requests for this?

**Comment by dungmv** [comment]
this feature can make editor load custom from form url?
if we have large quantity fonts, 1000 or more. it can't store on local and we have to store it on the server.

**Comment by salgum1114** [comment]
@b-b0t 

I wil not support because this project don't require it.
If you really want, fork and customize the project.

@dungmv 

You be right.

**Comment by b-b0t** [comment]
@salgum1114 thanks for clarifying.
