### ISSUE TITLE
Arrows and lines disappear in preview and in uploaded json

### ISSUE THREAD

**Issue by flex123** [salgum1114/react-design-editor#157]
**Describe the bug**
I added a line and an arrow to the canvas and did a preview.  Both the line and arrow disappeared in the preview.  I also tried downloading the canvas as a Json file and uploading it again.  Same issue happened.

![image](https://user-images.githubusercontent.com/10717743/73744900-cac9c300-471f-11ea-99da-bd63a42fe590.png)

![image](https://user-images.githubusercontent.com/10717743/73745095-3744c200-4720-11ea-9d50-c7127884b0bb.png)

**Comment by salgum1114** [comment]
@flex123 

I'd fix bug. Please check it.
