### ISSUE TITLE
[Question] How to add Chart Option from settings?

### ISSUE THREAD

**Issue by markblasdls** [salgum1114/react-design-editor#182]
Good Day! I tried adding options to chart via settings, but I don't know the is the proper format. How can I properly add option values? Thankyou!

**Comment by salgum1114** [comment]
@markblasdls 

https://echarts.apache.org/examples/en/index.html

**Comment by markblasdls** [comment]
This sample code works for me, thanks a lot @salgum1114. You're the best! 

```
return {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }]
};
```
