### ISSUE TITLE
just doubts

### ISSUE THREAD

**Issue by rodgomesc** [salgum1114/react-design-editor#185]
if you were starting this project today, would you treat a different aproach about how pass canfasRef  between  each component?

**Comment by ahmetcetin** [comment]
indeed, canvasRef passed to many components, but in fact it's not used at all in most of them, all updates are handled ImageMapEditor.js. It can be deleted from NodeProperties and all its children. Also from MapProperty.js and ImageProperty.js. I'm not sure if it's necessary in MapProperties.js or not as it's used to determine if canvas added to dom or not. 

Passing canvasRef to MapProperties and NodeProperties is ok, as they are direct children of ImageMapEditor where canvasRef defined.

**Comment by salgum1114** [comment]
@rodgomesc 

Naturally, I can try it in a variety of ways. (Context, Custom hook...)
But, right now, I don't feel it is necessary.

**Comment by rodgomesc** [comment]
thank you guys for the feedback, amazing project
