### ISSUE TITLE
[Bug] Save image with only "workarea" content without the container

### ISSUE THREAD

**Issue by rsm23** [salgum1114/react-design-editor#186]
I want to save an image of the creation but without the gray background, only the workarea with the element inside it.

This `saveCanvasImage` function saves what's visible on the workarea, event if the creation is zoomed in the resulting image will have the creation cropped out.

![New Image (13)](https://user-images.githubusercontent.com/2084708/83887268-80496900-a748-11ea-9f65-014a54cd5c2c.jpg)

What I want to do is to export an image with the dimensions of the workarea (with the elements inside it of course) without anything else (Only the white portion from the image above)

I hope my english suffices to explain my issue

**Comment by JosiahThobejane** [comment]
Hi @rsm23 hope you doing well out there. did you manage to sort this one out? also looking to do a similar thing

**Comment by shuwenjunn** [comment]
> Hi @rsm23 hope you doing well out there. did you manage to sort this one out? also looking to do a similar thing

did you solve the question?

**Comment by gabrielenosso** [comment]
This bug should be probably reopened.
Having the same issue.
