### ISSUE TITLE
[Docs] using WorkflowEditor as a library

### ISSUE THREAD

**Issue by hauntingEcho** [salgum1114/react-design-editor#189]
We're looking into using WorkflowEditor in another project, however per #141 there's not much documentation on doing so yet.

It sounds like the Canvas is what's exported by the NPM package.  Would the best path forward to re-use the WorkflowEditor component be to fork that part of the project?

**Comment by salgum1114** [comment]
@hauntingEcho 

It is best to download the ReactDesignEditor package and directly modify and use the WorkflowEditor using the Canvas component.

**Comment by hauntingEcho** [comment]
that makes sense - thanks!
