### ISSUE TITLE
[Question] idea or a lead on how to bring elements(chart) Down or Up?

### ISSUE THREAD

**Issue by markblasdls** [salgum1114/react-design-editor#195]
So currently the elements sample the chart is always on top, can you share if you have any leads for me to look to on how I can bring it down or up? I am really struggling on this in almost a month now. Thank you so much!

**Comment by salgum1114** [comment]
@markblasdls 

Sorry I'm late. In the case of Element, it is difficult to adjust the order because it is above the Canvas object.

**Comment by markblasdls** [comment]
@salgum1114 Thanks for your update, I guess  I need to dive deeper on this. I hope I can make it and will share here if I get a good result.. Thanks again..
