### ISSUE TITLE
[Bug] can't switch between 2 mode grab and selection on footer toolbar

### ISSUE THREAD

**Issue by dungmv** [salgum1114/react-design-editor#197]
In mode MapEditor, I can't switch between 2 mode grab and selection on footer toolbar, When I add 
```this.props.canvasRef.handler.interactionHandler.selection();``` and  ```this.props.canvasRef.handler.interactionHandler.grab();``` to 2 line
https://github.com/salgum1114/react-design-editor/blob/master/src/components/imagemap/ImageMapFooterToolbar.js#L63
https://github.com/salgum1114/react-design-editor/blob/master/src/components/imagemap/ImageMapFooterToolbar.js#L56
it's work!

**Comment by salgum1114** [comment]
@dungmv 

Thanks! I will fixes soon.
