### ISSUE TITLE
how to use? after yarn add react-design-editor

### ISSUE THREAD

**Issue by yumanfeng** [salgum1114/react-design-editor#198]
how to use? after yarn add react-design-editor

**Comment by salgum1114** [comment]
You can use it like below code:

```javascript
import { Canvas } from 'react-design-editor';

...
...

render() {
  return (
    <Canvas {...props} />
  )
}
```

Also, you can more example: `WorkflowEditor.js`, `ImageMapEditor.js`

**Comment by weihomechen** [comment]
thx, i got it.

**Comment by omeryaldirgan** [comment]
Hi,
How can I use ImageMapEditor

**Comment by salgum1114** [comment]
@omeryaldirgan 

Unfortunately, `ImageMapEditor` and `WorkflowEditor` are not modularized as components. It is simply an example.
