### ISSUE TITLE
Save entire map as an image

### ISSUE THREAD

**Issue by sugarman9907** [salgum1114/react-design-editor#213]
Hello. Thank you for your excellent map editor.
While using your map editor, I noticed "Save Image" button only saves content that user sees in "canvas".
We can upload large resolution image as background image.
And need to work on map by moving & moving if we can't see entire part with lowest minimize (30%).
IF you could add "Save map" button that saves entire "workarea" with all contents in & workarea resolution, that will be good.

**Comment by salgum1114** [comment]
solved #234
