### ISSUE TITLE
[Feature] Make react and react-dom to devDependencies

### ISSUE THREAD

**Issue by pikokr** [salgum1114/react-design-editor#228]
**Is your feature request related to a problem? Please describe.**

I'm getting errors when I use this module with react beta version.

**Describe the solution you'd like**
move react and react-dom to devDependencies in package.json

**Describe alternatives you've considered**
nope

**Comment by Othman2001** [comment]
@pikokr  why you need react and react-dom as dev dependencies ?

**Comment by Othman2001** [comment]
@pikokr react and react-dom  they are important packages which means you need them in the production bundle, so making them as devDependecies is not the best option at all 
thanks 😊
