### ISSUE TITLE
[Bug] Library is still react 16 and causing issues with react 16

### ISSUE THREAD

**Issue by Thomas-plusonex** [salgum1114/react-design-editor#229]
I have a react project which is using react version 17.
When I install and try use the canvas I get the following issue:
![image](https://user-images.githubusercontent.com/97668530/150952912-b5f95a7f-fb49-4d69-8247-bdb265dfdddb.png)

This is how I am using the library for now:
```
import React from "react";
import { Canvas } from "react-design-editor";

function ImageMapEditor() {
  return (<>
    <Canvas />
  </>)
}

export default ImageMapEditor;
```

**Comment by AndreasBurbach** [comment]
This project is not intended to be easy to install and use. If you want to move elements inside the screen like in the editor use fabrij.js directly instead of using this project.

**Comment by Thomas-plusonex** [comment]
Seems a bit counter productive when I can't even load just the initial Canvas object which is required for the example editor I want to go through, heck looks like all the editors need the Canvas object

**Comment by salgum1114** [comment]
@Thomas-plusonex 

I haven't tried running it in react v17 yet.
It is expected that work will be required.
