### ISSUE TITLE
[Question] How to get svg?

### ISSUE THREAD

**Issue by zztrk** [salgum1114/react-design-editor#85]
when  i am calling  canvasRef.canvas.toSVG() function in ImageMapEditor,

getting this error in fabricjs file:
http://prntscr.com/mgahxr

so how i export svg format like json export

**Comment by salgum1114** [comment]
Hi zttrk.

If the workarea image is empty, it will not work because it can not compute `_element.width.`

So please retry after uploading the image.

![image_upload](https://user-images.githubusercontent.com/19975642/52203444-9628ee80-28b4-11e9-8cc5-35fb79828caf.PNG)

**Comment by zztrk** [comment]
Hi salgum1114, , didn't get the error you said. Is there any way get svg without upload the image?

Thanks you so much

**Comment by salgum1114** [comment]
Hi zztrk.

Cannot toSVG() without image upload because current workarea object is 'fabric.Image'.

But, this is possible if workarea object is changed to 'fabric.Rect' !!

**Comment by zztrk** [comment]
Thank for repsonse. I will try workarea object changed to fabric.Rect and write to result here
