### ISSUE TITLE
[Question] How to load base64 via ImageProperty

### ISSUE THREAD

**Issue by zztrk** [salgum1114/react-design-editor#91]
Hi, my crop & compression components result base64. I want to use that component before image load.

When i use

this.canvasRef.workareaHandlers.setImage('BASE64_STRING') in onChangeWokarea function

getting this error

![image](https://user-images.githubusercontent.com/6421174/55213694-2a546980-5205-11e9-809a-3c6c89e4a8ae.png)

**Comment by salgum1114** [comment]
Hi, zztrk!

I'll check it out and let you know.

**Comment by zztrk** [comment]
Thank you, i'm waiting for your answer.

**Comment by salgum1114** [comment]
Do you want to use the cropped base64 image in your workarea?

Can you show me the code you are writing?

**Comment by zztrk** [comment]
Yes, i want to use cropped data(base64) 

![image](https://user-images.githubusercontent.com/6421174/55215957-7a82fa00-520c-11e9-9e90-977e3710c031.png)


![image](https://user-images.githubusercontent.com/6421174/55216004-9e464000-520c-11e9-88ae-2b193d4848d0.png)

**Comment by salgum1114** [comment]
![image](https://user-images.githubusercontent.com/19975642/55217041-c734f800-5241-11e9-8f8b-d1f21601c0bc.png)

**Is this what you want to use?**

**Comment by zztrk** [comment]
Thank you so much, i found my mistake. I changed imageLoadType to src and it worked :)
👍 👍 👍

**Comment by salgum1114** [comment]
👍 Ask me anytime ^^
